server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.140.68:3306/cdc?serverTimezone=UTC
    password: 123456
    username: root



logging:
  level:
    com.cdc.train: debug
  config: classpath:log4j-spring.xml

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl